export const menuItemsData = [
  {
    id: 1,
    name: 'همبرگر',
    info: ' دو عدد برگر 160 گرمی ,ژامبن ,  گوجه ,پنیر گودا , پیاز , سبزیجات تازه , نان کنجدی',
    price: 110000,
    img:require('../../../images/bigBurger.png') ,
  },
  {
    id: 2,
    name: 'سالاد آسیایی',
    info: ' چهار عدد فیله مرغ , دو عدد تخم مرغ آب پز , گوجه گیلاسی , کلم , نخد فرنگی , ذرت , کاهو',
    price: 99000,
    img:require('../../../images/bowl1.png') ,
  },
  {
    id: 3,
    name: 'سالاد بلژیکی',
    info: 'ذرت , گوجه , سيب زميني , سير تازه , هویج , کلم بروکلی , نمك , فلفل سياه , آويشن',
    price: 95000,
    img:require('../../../images/bowl2.png') ,
  },
  {
    id: 4,
    name: 'پاستا با سس بشامل',
    info: 'سینه مرغ 2 عدد , پاستا فرمی 150 گرم , قارچ , گوشت چرخ کرده , سس مخصوص , ادویه مخصوص',
    price: 99000 ,
    img:require('../../../images/bowl3.png') ,
  },
  {
    id: 5,
    name: 'پاستا پروانه ای',
    info: 'هویج , گوجه فرنگی , جعفری تازه , ریحان تازه , سیر , سس گوجه فرنگی , پنیر پارمسان , نمک و فلفل',
    price: 79000,
    img:require('../../../images/bowl4.png') ,
  },
  {
    id: 6,
    name: 'کاسه میوه ای',
    info: 'توت فرنگی , گیلاس , بلوبری , کیوی , انبه , پرتقال , شلیل , موز , اناناس , انگور , سیب',
    price: 60000,
    img:require('../../../images/fruits.png') ,
  },
  {
    id: 7,
    name: 'کاسه غلات گرانولا',
    info: 'گرانولا یک خوراکی خوشمزه و خوش طعم است که به عنوان صبحانه و میان وعده مصرف می شود.',
    price: 35000,
    img:require('../../../images/granola cereal bowl.png') ,
  },
  {
    id: 8,
    name: 'کاسه میوه شکلاتی',
    info: 'موز , توت فرنگی , بلوبری , شکلات آب شده , مغز گردو , غلات , عسل , شهد انگور',
    price:68000,
    img:require('../../../images/kisspng-aa-na-tigela-smoothie-aa-palm-bowl-apple-j-goji-berry-5b306ffe7baf07.9992682215299010545066.png') ,
  },
  {
    id: 9,
    name: 'اسموتی',
    info: 'اسموتی، یک وعده‌ی غذایی خوب برای بعد از ورزش است. خود را به یک اسموتی خوشمزه دعوت کنید. ',
    price: 47000,
    img:require('../../../images/kisspng-aa-na-tigela-smoothie-breakfast-juice-health-s-acai-bowl-5b11d2604db908.6695630315278946243184.png') ,
  },
  {
    id: 10,
    name: 'غلات صبحانه',
    info: 'گندم , جو , برنج , یولاف , ذرت , خرما , کشکش , میوه های خشک شده , مغز پسته و بادام',
    price: 52000,
    img:require('../../../images/kisspng-breakfast-cereal-pizza-muesli-meze-vegetarian-cuis-granola-5ac48d852aeb69.1891892315228307251758.png') ,
  },
  {
    id: 11,
    name: 'پاستا سبزیجات',
    info: 'هویج , گوجه فرنگی , کلم بروکلی , جعفری تازه , ریحان تازه , سیر , سس گوجه فرنگی , پنیر پارمسان , نمک و فلفل',
    price: 63000,
    img:require( '../../../images/kisspng-cuisine-of-hawaii-l-l-hawaiian-barbecue-shrimp-gam-frozen-chicken-5b1e62f3a9e035.2766282415287180676958.png'),
  },
  {
    id: 12,
    name: 'مرغ و سبزیجات',
    info: 'هشت تکه فیله مرغ سوخاری , گوجه گیلاسی , مارچوبه , خیار , سبزیجات تازه , آویشن',
    price: 65000,
    img:require('../../../images/kisspng-fried-chicken-lemon-chicken-chicken-meat-fine-dining-chicken-meat-5a940a1b75aa22.821205431519651355482.png') ,
  },
  {
    id: 13,
    name: 'سالاد یونانی',
    info: 'پیاز قرمز , پنیر فتا , زیتون سیاه , خیار سالادی , فلفل دلمه ای , گوجه فرنگی , روغن زیتون',
    price: 40000,
    img:require('../../../images/kisspng-greek-salad-fruit-salad-spinach-salad-muesli-vegetable-salad-5a96f429ce9af3.7299622115198423458463.png') ,
  },
  {
    id: 14,
    name: 'سالاد سزار',
    info: 'کاهو , سس سزار , دو عدد فیله سوخاری , ترکیب سس مایونز و خردل , چاشنی فرانسوی , زیتون و گوجه گیلاسی',
    price: 115000,
    img:require('../../../images/kisspng-hamburger-street-food-seafood-fast-food-delicious-food-5a75083cceaf41.2676743415176192608466.png') ,
  },
  {
    id: 15,
    name: 'سالاد اسرائیلی',
    info: 'خیار سالادی , گوجه فرنگی , پیاز , فلفل دلمه ای , لیمو ترش تازه , روغن زیتون , نمک , پودر گل سرخ',
    price: 30000,
    img:require('../../../images/kisspng-israeli-salad-european-cuisine.png') ,
  },
  {
    id: 16,
    name: 'استیک',
    info: '600 الی 700 گرم استیک شیشلیک گوساله , سس مخصوص , لیمو ترش , بیبی چیلی , سیب زمینی سرخ کرده , سزیجات',
    price: 150000,
    img:require( '../../../images/kisspng-italian-cuisine-pizza-pasta-food-plate-healthy-food-5abb864701e2b7.3892346415222390470077.png'),
  },
  {
    id: 17,
    name: 'پیتزا',
    info: '250 گرم گوشت چرخ کرده , قارچ , 220 گرم خمیر , کف سس مخصوص , فلفل دلمه ای , پنیر',
    price: 169000,
    img:require('../../../images/pizza.png') ,
  },
];